language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure : change 


before_install:
  - rvm install 2.5
  - rvm use 2.5
  - gem update --system
  - gem install bundler 
  - bundle check || bundle install 

install:
  - npm install -g firebase-tools 

script: 
  - jekyll build 

after_success:
  - firebase deploy --token "$FIREBASE_API_TOKEN" 

sudo: false # route your build to the container-based infrastructure for a faster build